[package]
name = "fylo-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
fylo-query = { version = "0.1.0", path = "../crates/fylo-query" }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "query_snapshot"
path = "fuzz_targets/query_snapshot.rs"
test = false
doc = false
bench = false

[workspace]
