[package]
name = "fylo-storage-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
fylo-format = { version = "0.1.0", path = "../fylo-format" }
fylo-query = { version = "0.1.0", path = "../fylo-query" }
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(unix)'.dependencies]
xattr.workspace = true

[lints]
workspace = true
